### ISSUE TITLE
Error while setting up telenet_telemeter platform for sensor - AssertionError

### ISSUE THREAD

**Issue by tjorim** [myTselection/telenet_telemeter#15]
```
Logger: homeassistant.components.sensor
Source: custom_components/telenet_telemeter/utils.py:81
Integration: Sensor (documentation, issues)
First occurred: 12:45:12 AM (1 occurrences)
Last logged: 12:45:12 AM

Error while setting up telenet_telemeter platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 110, in async_setup_entry
    await dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 51, in dry_setup
    await data_internet._forced_update()
  File "/config/custom_components/telenet_telemeter/sensor.py", line 144, in _forced_update
    await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 144, in <lambda>
    await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/config/custom_components/telenet_telemeter/utils.py", line 81, in login
    assert response.status_code == 200
AssertionError
```

**Comment by myTselection** [comment]
Just tested again myself and login is still working fine for me. 
Looking at your error, it might be a wrong username/password is provided. Make sure to use an email address as username, the old username login is no longer supported by Telenet. You can try to login on the website of telenet itself 'Mijn Telenet' to validate your credentials are correct.
But some Telenet backend changes are ongoing these days too, so it might be your account is already migrated to their new backend. This integration is not yet made compatible with the new Telenet backend. As soon as migration is completed at their side, I'll take a look into it...

**Comment by myTselection** [comment]
Now I'm getting similar exception. Probably Telenet backend migrations are progressing.
Will validate in coming days and try to make the integration compatibel with Telenet backend again.

**Comment by myTselection** [comment]
hmm, just wanted to start in depth investigation, but I do notice it works again without any changes. Not sure if Telenet has restored their backend and if any changes are still to be expected. But for now, a simple reload or HA restart solved it for me.

@arszagi: sorry, I have no view on Telenet Business account differences vs std. Feel free to open another ticket If you would see any specific exception in the logs related to business account.

**Comment by tjorim** [comment]
Just tried it again but still getting the assertion error:

```
Logger: homeassistant.components.sensor
Source: custom_components/telenet_telemeter/utils.py:81
Integration: Sensor (documentation, issues)
First occurred: 06:24:46 (2 occurrences)
Last logged: 06:27:08

Error while setting up telenet_telemeter platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 113, in async_setup_entry
    await dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 52, in dry_setup
    await data_internet._forced_update()
  File "/config/custom_components/telenet_telemeter/sensor.py", line 147, in _forced_update
    await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 147, in <lambda>
    await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/config/custom_components/telenet_telemeter/utils.py", line 81, in login
    assert response.status_code == 200
AssertionError
```

**Comment by myTselection** [comment]
I'll check again in couple of days, it seems Telenet is planning backend changes again: 

> Mijn Telenet tijdelijk niet beschikbaar
> 
> Van zaterdag 11/3 22u tot zondag 12/3 20u verbeteren we onze diensten. Tijdens de werken kan je Mijn Telenet niet gebruiken.

**Comment by myTselection** [comment]
are you sure you are using the correct username and password?
Since some time Telenet doesn't support the old usernames any longer, only email address is supported.
Please confirm your credentials by logging out and in on the Telenet website itself.

**Comment by arszagi** [comment]
@myTselection , i have Telenet business account, but the error is the same. Any idea?

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 113, in async_setup_entry
    await dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 52, in dry_setup
    await data_internet._forced_update()
  File "/config/custom_components/telenet_telemeter/sensor.py", line 147, in _forced_update
    await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 147, in <lambda>
    await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/config/custom_components/telenet_telemeter/utils.py", line 81, in login
    assert response.status_code == 200
AssertionError`

**Comment by tjorim** [comment]
Yes, I can access this information with the same credentials:
![image](https://user-images.githubusercontent.com/1294876/227389652-cc673012-fe2a-4fa4-81f5-647e36e13a94.png)

**Comment by myTselection** [comment]
Strange, can't explain. Could you try to change your Telenet password? Maybe some special character in your password is not handled correctly...

**Comment by myTselection** [comment]
dear, was this issue resolved for you? Any idea what was the root cause? I see similar issue reported by another user...

**Comment by myTselection** [comment]
expected this is no longer an issue
