### ISSUE TITLE
wifree usage update fails

### ISSUE THREAD

**Issue by myTselection** [myTselection/telenet_telemeter#36]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 957, in async_device_update
    await self.async_update()
  File "/config/custom_components/telenet_telemeter/sensor.py", line 388, in async_update
    self._wifree_usage = self._data._telemeter.get('internet').get('wifreeUsage').get('usedUnits')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
2023-11-21 14:29:12.094 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.telenet_telemeter_peak_w******* fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 957, in async_device_update
    await self.async_update()
  File "/config/custom_components/telenet_telemeter/sensor.py", line 627, in async_update
    self._wifree_usage = self._data._telemeter.get('internet').get('wifreeUsage').get('usedUnits')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by thomasdbnet** [comment]
wifree is a service wich the provider telenet has stopped since beginning november it does not exist anymore

**Comment by myTselection** [comment]
thx, I know ;) that's why I removed it in R1.5.0
