### ISSUE TITLE
Error in logs: Update for switch.telenet_telemeter_wifi fails

### ISSUE THREAD

**Issue by Just-inc-ace** [myTselection/telenet_telemeter#48]
Since a couple of days I get following error in my log:

'2024-05-23 14:32:10.301 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.telenet_telemeter_wifi fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 950, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1293, in async_device_update
    await self.async_update()
  File "/config/custom_components/telenet_telemeter/switch.py", line 220, in async_update
    await self._data.update()
  File "/config/custom_components/telenet_telemeter/switch.py", line 167, in update
    await self._update()
  File "/config/custom_components/telenet_telemeter/switch.py", line 160, in _update
    await self.force_update()
  File "/config/custom_components/telenet_telemeter/switch.py", line 139, in force_update
    productServiceDetails = await self._hass.async_add_executor_job(lambda: self._session.productService(internetProductIdentifier, "INTERNET"))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/telenet_telemeter/switch.py", line 139, in <lambda>
    productServiceDetails = await self._hass.async_add_executor_job(lambda: self._session.productService(internetProductIdentifier, "INTERNET"))
                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/telenet_telemeter/utils.py", line 167, in productService
    response = self.callTelenet(f"https://api.prd.telenet.be/ocapi/public/api/product-service/v1/products/{productIdentifier}?producttype={productType.lower()}","productService")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/telenet_telemeter/utils.py", line 80, in callTelenet
    assert response.status_code == expectedStatusCode
AssertionError'

After enabling debuggin it seems this is the entry before this error:
' DEBUG (SyncWorker_49) [custom_components.telenet_telemeter.utils] [productService] http status code = 500 (expecting 200)'

Any idea?

**Comment by myTselection** [comment]
Will look into it, I don't use the switch that often myself ;)
