### ISSUE TITLE
callTelenet failed en other errors

### ISSUE THREAD

**Issue by screenagerbe** [myTselection/telenet_telemeter#54]
Current situation:
As of 07-11-2024 00:05 my HA instance cannot poll the Telenet api anymore.
![image](https://github.com/user-attachments/assets/d578faa3-7ff8-4bea-aec9-7ca7ec82d96b)

Remarks: 

- Our Telenet subscription starts at the 7th of the month, so the values are reset each month on the 7th at 00:05.
- Reloading the integration results in the same error
- Removing and reinstalling the integration results also in the same error

Error in the log files after reloading/installing the Telenet Integration:

```
This error originated from a custom integration.

Logger: custom_components.telenet_telemeter.utils
Source: custom_components/telenet_telemeter/utils.py:83
integration: Telenet Telemeter (documentation, issues)
First occurred: 07:27:50 (2 occurrences)
Last logged: 07:27:50

callTelenet failed, trying once more:
```

```
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:365
integration: Switch (documentation, issues)
First occurred: 07:27:50 (1 occurrences)
Last logged: 07:27:50

Error while setting up telenet_telemeter platform for switch
Traceback (most recent call last):
  File "/config/custom_components/telenet_telemeter/utils.py", line 81, in callTelenet
    assert response.status_code == expectedStatusCode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/telenet_telemeter/switch.py", line 26, in async_setup_entry
    await data.force_update()
  File "/config/custom_components/telenet_telemeter/switch.py", line 143, in force_update
    await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/telenet_telemeter/switch.py", line 143, in <lambda>
    await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/telenet_telemeter/utils.py", line 119, in login
    self.callTelenet("https://api.prd.telenet.be/ocapi/oauth/userdetails","login")
  File "/config/custom_components/telenet_telemeter/utils.py", line 103, in callTelenet
    assert response.status_code == expectedStatusCode
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:365
integration: Sensor (documentation, issues)
First occurred: 07:27:50 (1 occurrences)
Last logged: 07:27:50

Error while setting up telenet_telemeter platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/telenet_telemeter/utils.py", line 81, in callTelenet
    assert response.status_code == expectedStatusCode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 121, in async_setup_entry
    await dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 52, in dry_setup
    await data_internet._forced_update()
  File "/config/custom_components/telenet_telemeter/sensor.py", line 170, in _forced_update
    await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/telenet_telemeter/sensor.py", line 170, in <lambda>
    await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/telenet_telemeter/utils.py", line 119, in login
    self.callTelenet("https://api.prd.telenet.be/ocapi/oauth/userdetails","login")
  File "/config/custom_components/telenet_telemeter/utils.py", line 103, in callTelenet
    assert response.status_code == expectedStatusCode
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

I've got the suspicion Telenet has changed something, but I do not know what exactly

**Comment by myTselection** [comment]
Thx for reporting. I see similar issue in my own sensor now, probably some changes in Telenet API. Will have to investigate...

**Comment by myTselection** [comment]
authentication scheme changes, will require to redo the reverse engineering to simulate this new authentication scheme

**Comment by Lem0nz** [comment]
Just checking in of we hier ergens info kunnen voorzien om u te helpen troubleshooten?
Triest om hem zo te zien staan in het dashboard :-D

![Image](https://github.com/user-attachments/assets/bf743db9-35a9-41a5-843b-3db41b8d4a78)

**Comment by PW999** [comment]
@myTselection I managed to reverse engineer the login flow.

```
import requests
import requests
import logging
import re
import json

# These two lines enable debugging at httplib level (requests->urllib3->http.client)
# You will see the REQUEST, including HEADERS and DATA, and RESPONSE with HEADERS but without DATA.
# The only thing missing will be the response.body which is not logged.
# try:
#     import http.client as http_client
# except ImportError:
#     # Python 2
#     import httplib as http_client
# http_client.HTTPConnection.debuglevel = 1

# #You must initialize logging, otherwise you'll not see debug output.
# logging.basicConfig()
# logging.getLogger().setLevel(logging.DEBUG)


if __name__ == "__main__":
    email=""
    password=""

    s = requests.Session()
    s.headers["Accept"] = "*/*"
    s.headers["User-Agent"] = "Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0"

    s.headers["x-alt-referer"] = "https://www2.telenet.be/residential/nl/mijn-telenet/"
    s.headers["X-Requested-With"] = "XMLHttpRequest"
    s.headers["Origin"] = "https://www2.telenet.be"
    s.headers["Referrer"] = "https://www2.telenet.be"  # Might not be needed
    
    # Check if already logged in, if not, get the basic cookies. Also returns a nonce and state for later use
    userdetails = s.get("https://api.prd.telenet.be/ocapi/oauth/userdetails")
    print(f"UserDetails: {userdetails.status_code}")
    assert userdetails.status_code == 401
    
    # allow_redirects=False for debugging purposes
    a = s.get(
        url="https://api.prd.telenet.be/ocapi/login/authorization/telenet_be?lang=nl&style_hint=care&targetUrl=https://www2.telenet.be/residential/nl/mytelenet.html",
        allow_redirects=False
    )
    print(f"Start: {a.status_code}")
    assert a.status_code == 302
    assert "secure.telenet.be" in a.headers.get("Location") 

    # This HTML code contains the initial stateToken that's encoded
    body_with_token = s.get(a.headers.get("Location")).text
    token_matcher = re.search('"stateToken":"(.*)","helpLinks"', body_with_token) 
    state_token_encoded = token_matcher.group(1)
    state_token_decoded = state_token_encoded.encode('latin1').decode('unicode_escape')
    
    # Start the login flow
    nonce = userdetails.text.split(",")[1]
    state = userdetails.text.split(",")[0]
    url = "https://api.prd.telenet.be/ocapi/login/authorization/telenet_be?client_id=telenet_be&response_type=code&claims={\"id_token\":{\"http://telenet.be/claims/roles\":null,\"http://telenet.be/claims/licenses\":null}}&lang=nl&nonce=" + nonce + "&state=" + state + "&prompt=none"
    redirect1 = s.get(
        url=url,
        allow_redirects=False
    )
    print(f"Start2: {redirect1.status_code}")
    assert redirect1.status_code == 302
    s.get(redirect1.headers.get("Location"))
    
    # Probably not needed, but can be usefull to log. Also not sure if "enabled" means that there is maintenance or not
    assert s.get("https://api.prd.telenet.be/omapi/public/publicconfigs/maintenance_ocapi").json()["enabled"] == False
    
    # Start the introspection (whatever it may be)
    state = s.post(
        url="https://secure.telenet.be/idp/idx/introspect",
        json={"stateToken": state_token_decoded},
    )
    print(f"Introspect: {state.status_code}")
    assert state.status_code == 200
    state_handle = state.json()['stateHandle']  # THIS WILL CHANGE EVERYTIME YOU PASS IT
    
    # I don't know if this is needed, but won't harm I guess, also less suss if there is a fingerprint
    assert s.get("https://secure.telenet.be/auth/services/devicefingerprint").status_code == 200
    
    # Again, there's nothing we do with this nonce
    new_nonce = s.post("https://secure.telenet.be/api/v1/internal/device/nonce").json()
    
    # Start the identify steps (again, might be possible to skip this ?)
    identify = s.post(
        url="https://secure.telenet.be/idp/idx/identify", 
        json={'identifier': email, 'stateHandle': state_handle}
    )
    print(f"Identify: {identify.status_code}")
    assert identify.status_code == 200
    state_handle = identify.json()['stateHandle']

    # Start the login challenge
    challenge = s.post(
        url="https://secure.telenet.be/idp/idx/challenge",
        json={
            "authenticator":
                {"id":"aut914ye006Pm8a7e417"},
                "stateHandle":state_handle}
    )
    print(f"Challenge: {challenge.status_code}")
    assert challenge.status_code == 200
    state_handle = challenge.json()['stateHandle']

    # Answer the challenge
    answer = s.post(
        url="https://secure.telenet.be/idp/idx/challenge/answer",
        json={
            "credentials":
                {"passcode":password},
                "stateHandle":state_handle}
    )
    print(f"Answer: {answer.status_code}")
    assert answer.status_code == 200

    # Final step, this is needed
    success = s.get(answer.json()["success"]["href"])
    print(f"Success: {success.status_code}")
    assert success.status_code == 200   # it'll probably redirect once more

    #Just a check
    usage = s.get("https://api.prd.telenet.be/ocapi/public/api/product-service/v1/products/internet/aa12593/usage?fromDate=2025-04-11&toDate=2025-05-10")
    print(usage.text)
    assert usage.status_code == 200
    
```

There's probably some endpoints that we can skip, but I'm not going to test my luck today, don't want Telenet to ban me 🔨

**Comment by myTselection** [comment]
Nice! Thx for this, will try to integrate asap

**Comment by myTselection** [comment]
fixed in R2.0
